export interface Hotkeys<T> {
    OPEN_IMAGE_SEARCH: T,
    HIDE: T,
    MARK_AS_KNOWN: T,
    DELETE_CARD: T,
    QUIZ_RESULT_EASY: T,
    QUIZ_RESULT_MEDIUM: T,
    QUIZ_RESULT_HARD: T,
    RECORD_QUIZ_WORD: T,
    REQUEST_EDIT_WORD: T,
    ADVANCE_QUIZ: T,
    HIDE_VIDEO: T,

    PRONUNCIATION_RECORD_SUCCESS: T
}