export {VideoMetadataDto} from "../video_metadata/video-metadata.dto";
export {DocumentViewDto} from '../documents/document-view.dto'
export {DocumentToBeSavedDto} from "../documents/document-to-be-saved.dto";
export {DocumentToBeDeletedDto} from '../documents/document-to-be-deleted.dto';
export {AvailableDocumentDto} from '../documents/available-document.dto'
export {TranslateRequestDto} from '../translate/translate-request-dto';
export {TransliterateRequestDto} from '../translate/transliterate-request.dto';
export {TransliterateResponseDto} from '../translate/transliterate-response.dto';
export {ImageObject} from "@azure/cognitiveservices-imagesearch/src/models/index";
