export const loadingBackdropTypography = 'loading-backdrop-typography';
export const annotatedAndTranslated = 'annotated_and_translated'
export const documentSelectionRow = 'document-selection-row';
export const quizCardTableRow = `quiz-card-table-row`;
export const quizCardTableRowWord = "quizCardTableRowWord";
export const quizCardTableRowRecognitions = 'quizCardTableRowRecognitions';
export const quizCardTableRowCounts = 'quizCardTableRowCounts';
export const quizCardTableRowLastAnswer = 'quizCardTableRowLastAnswer';
export const fileChooser = 'btn-upload';
export const uploadProgressBar = 'uploadProgressBar';
export const frequencyDocumentProgress = 'frequencyDocumentProgress';
export const frequencyDocumentProgressPrefix = 'frequencyDocumentProgress';
export const QUIZ_BUTTON_HARD = 'quiz-button-hard';
export const QUIZ_BUTTON_MEDIUM = 'quiz-button-medium';
export const QUIZ_BUTTON_EASY = 'quiz-button-easy';
export const QUIZ_BUTTON_IGNORE = 'quiz-button-hide';
export const unrecognizedCount = 'unrecognized-count';
export const somewhatRecognizedCount = 'somehwat-recognized-count';
export const recognizedCount = 'recognized-count';
export const frequencyDocumentList = 'frequencyDocumentList'
export const frequencyDocumentSelectRow = 'frequencyDocumentSelectRow';
export const hsk1Node = 'hsk1Node';
export const testNode1 = "闽中奇构";
export const testNode2 = "这辈子";
export const filterScheduleRows = 'filterScheduleRows';
export const manualHotkeyInput = 'manualHotkeyInput';
export const submitManualHotkeyButton = 'submitManualHotkeyButton';
export const manualQuizHiddenFieldConfigId = 'manualQuizHiddenFieldConfigId';
export const quizButtonReveal = 'quizButtonReveal'
export const quizCardImage = "quiz-card-image"
export const selectQuizCardImageButton = 'selectQuizCardImageButton';
export const quizCardTranslation = 'quizCardTranslation';
export const quizCardRomanization = 'quizCardRomanization';
export const quizCardDescription = 'quizCardDescription';
export const quizCardLearningLanguage = 'quiz-text';
export const uploadTextName = 'uploadTextName';
export const uploadTextArea = 'uploadTextArea';
export const uploadTextButton = 'uploadTextButton';
export const libraryRowToggleFrequency = 'libraryRowToggleFrequency';
export const libraryRowToggleReading = 'libraryRowToggleReading';
export const libraryRowDelete = 'libraryRowDelete';
export const libraryRow = 'libraryRow';
export const newWordLimitInput = 'newWordLimitInput';
export const noMoreQuizCards = 'noMoreQuizCards';
export const scheduleRowOpenWordButton = 'scheduleRowOpenWordButton';
export const wordCardCountRecords = 'wordCardCountRecords'
export const wordCardRecognitionRows =  'wordCardRecognitionRows '
export const wordCardDescription =  'wordCardDescription '
export const wordCardLearningLanguage =  'wordCardLearningLanguage '
export const wordCardRomanization =  'wordCardRomanization '
export const wordCardTranslation =  'wordCardTranslation '



